Repository LibreFoodPantry/BEAR-Necessities-Market, pull requests merged in 2019-03, with the labels that each got.

#41 Create LICENSE
  LICENSE
Labels: enhancement

#42 Completed current testing & Updated backend routing to use Namespaces
  .gitignore
  .travis.yml
  LICENSE
  LICENSE.md
  backend/__pycache__/__init__.cpython-36.pyc
  backend/__pycache__/app.cpython-36.pyc
  backend/__pycache__/config.cpython-36.pyc
  backend/app.py
  backend/config.py
  backend/extensions.py
  backend/models/users.py
  backend/resources/auth.py
  backend/resources/users.py
  frontend/src/containers/Users.js
  frontend/src/store/reducers/authenticate.js
  migrations/versions/6ca021205583_.py
  requirements.txt
  tests/base_case.py
  tests/conftest.py
  tests/functional/__init__.py
  tests/functional/test_auth.py
  tests/functional/test_users.py
  tests/pytest.ini
  tests/test_pytest.py
  tests/test_smtp.py
  tests/unit/__init__.py
  tests/unit/test_users_models.py
Labels: Testing

#57 Adding complete JWT auth. Added unit tests for auth. Updated react architecture.
  .travis.yml
  README.md
  backend/__pycache__/__init__.cpython-36.pyc
  backend/__pycache__/app.cpython-36.pyc
  backend/__pycache__/config.cpython-36.pyc
  backend/app.py
  backend/extensions.py
  backend/models/users.py
  backend/resources/auth.py
  backend/resources/users.py
  backend/utils/__pycache__/__init__.cpython-36.pyc
  backend/utils/__pycache__/decorators.cpython-36.pyc
  backend/utils/__pycache__/mail.cpython-36.pyc
  backend/utils/date.py
  backend/utils/decorators.py
  backend/utils/jwt.py
  backend/utils/mail.py
  docs/CODING_STANDARDS.md
  docs/architecture.md
  docs/documentation.md
  docs/getting-setup.md
  docs/helpful-commands.md
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.js
  frontend/src/_actions/alert.actions.js
  frontend/src/_actions/index.js
  frontend/src/_actions/user.actions.js
  frontend/src/_constants/alert.constants.js
  frontend/src/_constants/index.js
  frontend/src/_constants/user.constants.js
  frontend/src/_helpers/auth-header.js
  frontend/src/_helpers/history.js
  frontend/src/_helpers/index.js
  frontend/src/_reducers/alert.reducer.js
  frontend/src/_reducers/authenticate.js
  frontend/src/_reducers/index.js
  frontend/src/_reducers/stepCounter.js
  frontend/src/_reducers/users.js
  frontend/src/_services/index.js
  frontend/src/_services/user.service.js
  frontend/src/_store/store.js
  frontend/src/components/Header/Header.js
  frontend/src/components/Signin/form.js
  frontend/src/components/Signin/index.js
  frontend/src/containers/Home.js
  frontend/src/containers/Signin.js
  frontend/src/index.js
  frontend/src/layouts/MainLayout.js
  frontend/src/store/index.js
  frontend/src/store/reducers/authenticate.js
  media/logo-text.png
  media/logo.png
  tests/conftest.py
  tests/functional/test_auth.py
Labels: Integration, feature

#74 Revert "Adding complete JWT auth. Added unit tests for auth. Updated …
  .travis.yml
  CODING_STANDARDS.md
  README.md
  backend/__pycache__/__init__.cpython-36.pyc
  backend/__pycache__/app.cpython-36.pyc
  backend/__pycache__/config.cpython-36.pyc
  backend/app.py
  backend/extensions.py
  backend/models/users.py
  backend/resources/auth.py
  backend/resources/users.py
  backend/utils/__pycache__/__init__.cpython-36.pyc
  backend/utils/__pycache__/decorators.cpython-36.pyc
  backend/utils/__pycache__/mail.cpython-36.pyc
  backend/utils/date.py
  backend/utils/decorators.py
  backend/utils/jwt.py
  backend/utils/mail.py
  docs/architecture.md
  docs/documentation.md
  docs/getting-setup.md
  docs/helpful-commands.md
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.js
  frontend/src/_actions/alert.actions.js
  frontend/src/_actions/index.js
  frontend/src/_actions/user.actions.js
  frontend/src/_constants/alert.constants.js
  frontend/src/_constants/index.js
  frontend/src/_constants/user.constants.js
  frontend/src/_helpers/auth-header.js
  frontend/src/_helpers/history.js
  frontend/src/_helpers/index.js
  frontend/src/_reducers/alert.reducer.js
  frontend/src/_reducers/authenticate.js
  frontend/src/_services/index.js
  frontend/src/_services/user.service.js
  frontend/src/_store/store.js
  frontend/src/components/Header/Header.js
  frontend/src/components/Signin/form.js
  frontend/src/components/Signin/index.js
  frontend/src/containers/Home.js
  frontend/src/containers/Signin.js
  frontend/src/index.js
  frontend/src/layouts/MainLayout.js
  frontend/src/store/index.js
  frontend/src/store/reducers/authenticate.js
  frontend/src/store/reducers/index.js
  frontend/src/store/reducers/stepCounter.js
  frontend/src/store/reducers/users.js
  media/logo-text.png
  media/logo.png
  tests/conftest.py
  tests/functional/test_auth.py
Labels: bug
