Repository LibreFoodPantry/BEAR-Necessities-Market, pull requests merged in 2019-04, with the labels that each got.

#96 Fix for #95
  requirements.txt
Labels: needs review

#98 - Added `.gitattributes`, LF End-of-Lines only
  .gitattributes
Labels: needs review

#100 Lock python packages to current working versions #86
  README.md
  requirements-to-freeze.txt
  requirements.txt
Labels: blocker, needs review

#75 Email service
  README.md
  backend/app.py
  backend/config.py
  backend/utils/__init__.py
  backend/utils/mail.py
  docs/getting-setup.md
  migrations/versions/6ca021205583_.py
  requirements-to-freeze.txt
  requirements.txt
  tests/conftest.py
  tests/unit/test_mail.py
  yarn.lock
Labels: blocker
